# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: My Envio Indexer
unordered_multichain_mode: true
rollback_on_reorg: false
contracts:
  - name: PoolFactory
    handler: src/EventHandlers.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, bool indexed stable, address pool, uint256 unnamed)
      - event: SetCustomFee(address indexed pool, uint256 fee)
  - name: Pool
    handler: src/EventHandlers.ts
    events:
      - event: Sync(uint256 reserve0, uint256 reserve1)
      - event: Swap(address indexed sender, address indexed to, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out)
  - name: CLFactory
    handler: src/EventHandlers.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, int24 indexed tickSpacing, address pool)
  - name: Voter
    handler: src/EventHandlers.ts
    events:
      - event: GaugeCreated(address indexed poolFactory, address indexed votingRewardsFactory, address indexed gaugeFactory, address pool, address bribeVotingReward, address feeVotingReward, address gauge, address creator)
      - event: WhitelistToken(address indexed whitelister, address indexed token, bool indexed _bool)
  - name: BribeVotingReward
    handler: src/EventHandlers.ts
    events:
      - event: Deposit(address indexed from, uint256 indexed tokenId, uint256 amount)
      - event: NotifyReward(address indexed from, address indexed reward, uint256 indexed epoch, uint256 amount)
      - event: Withdraw(address indexed from, uint256 indexed tokenId, uint256 amount)
  - name: Gauge
    handler: src/EventHandlers.ts
    events:
      - event: NotifyReward(address indexed from, uint256 amount)
networks:
  - id: 10
    start_block: 0
    contracts:
      - name: PoolFactory
        address:
          - 0xF1046053aa5682b4F9a81b5481394DA16BE5FF5a
      - name: Voter
        address:
          - 0x41C914ee0c7E1A5edCD0295623e6dC557B5aBf3C
      - name: CLFactory
        address:
          - 0xCc0bDDB707055e04e497aB22a59c2aF4391cd12F
      # factory generated addresses
      - name: Pool
        address:
      - name: Gauge
        address:
      - name: BribeVotingReward
        address:
  - id: 8453
    start_block: 0
    contracts:
      - name: PoolFactory
        address:
          - 0x420DD381b31aEf6683db6B902084cB0FFECe40Da
      - name: Voter
        address:
          - 0x16613524e02ad97eDfeF371bC883F2F5d6C480A5
      - name: CLFactory
        address:
          - 0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A
      - name: Pool
        address:
      - name: Gauge
        address:
      - name: BribeVotingReward
        address:
